#!/bin/bash
# 
# video converter for youtube
 
usage() {
    test -n "$1" && echo "Error: $1"
    cat <<- EOT
Usage: $(basename $0) FILEIN FILEOUT
Convert any? video FILEIN to FILEOUT.avi
EOT
    exit
}

test $# == 0 && usage
test $# != 2 && usage "Bad number arguments"

filein="$1"
fileout="${2%.*}"

test -f $filein || usage "FILEIN must exists: abort"

rencode() {
# rencode in $1 width
    local f="${fileout}_$1.avi"
    test -f "$f" && { echo "file $f already exists!"; exit; }
    mencoder -quiet -ovc xvid -oac mp3lame -xvidencopts bitrate=2400 -vf scale=$1:-2 -o "${f}" $filein
}

rencode 720
rencode 1080



# vim:set ts=4 sw=4 sta ai nospell:

